defaults:
  - _self_
  - dataset: arithmetic
  - model: transformer
  - fsd_estimator: ground_truth

seed: 123
optimizer: adam
learning_rate: 1e-3
weight_decay: 0.1
batch_size: 32
train_epochs: 15
fsd_weight: 1
classwise: False

experiment_name: test
use_wandb: False
output_csv:
